/**
 * Razer REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChromaSdkInput_author.h
 *
 * 
 */

#ifndef ChromaSdkInput_author_H_
#define ChromaSdkInput_author_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace ChromaPackage {
namespace Model {

/// <summary>
/// 
/// </summary>
class  ChromaSdkInput_author
    : public ModelBase
{
public:
    ChromaSdkInput_author();
    virtual ~ChromaSdkInput_author();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ChromaSdkInput_author members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    void setName(utility::string_t value);
    bool nameIsSet() const;
    void unsetName();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getContact() const;
    void setContact(utility::string_t value);
    bool contactIsSet() const;
    void unsetContact();

protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
utility::string_t m_Contact;
    bool m_ContactIsSet;
};

}
}

#endif /* ChromaSdkInput_author_H_ */
