/**
 * Razer REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * PostChromaSdkResponse.h
 *
 * 
 */

#ifndef PostChromaSdkResponse_H_
#define PostChromaSdkResponse_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace ChromaPackage {
namespace Model {

/// <summary>
/// 
/// </summary>
class  PostChromaSdkResponse
    : public ModelBase
{
public:
    PostChromaSdkResponse();
    virtual ~PostChromaSdkResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PostChromaSdkResponse members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSessionid() const;
    void setSessionid(utility::string_t value);
    bool sessionidIsSet() const;
    void unsetSessionid();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUri() const;
    void setUri(utility::string_t value);
    bool uriIsSet() const;
    void unsetUri();

protected:
    utility::string_t m_Sessionid;
    bool m_SessionidIsSet;
utility::string_t m_Uri;
    bool m_UriIsSet;
};

}
}

#endif /* PostChromaSdkResponse_H_ */
