/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * EffectIdentifierResponse.h
 *
 * 
 */

#ifndef EffectIdentifierResponse_H_
#define EffectIdentifierResponse_H_


#include "ModelBase.h"

#include "EffectIdentifierResponse_results.h"
#include <vector>

namespace ChromaPackage {
namespace Model {

/// <summary>
/// 
/// </summary>
class  EffectIdentifierResponse
    : public ModelBase
{
public:
    EffectIdentifierResponse();
    virtual ~EffectIdentifierResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// EffectIdentifierResponse members

    /// <summary>
    /// 
    /// </summary>
    int32_t getResult() const;
    void setResult(int32_t value);
    bool resultIsSet() const;
    void unsetResult();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<EffectIdentifierResponse_results>>& getResults();
    bool resultsIsSet() const;
    void unsetResults();

protected:
    int32_t m_Result;
    bool m_ResultIsSet;
std::vector<std::shared_ptr<EffectIdentifierResponse_results>> m_Results;
    bool m_ResultsIsSet;
};

}
}

#endif /* EffectIdentifierResponse_H_ */
