/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * EffectInput.h
 *
 * JSON Data
 */

#ifndef EffectInput_H_
#define EffectInput_H_


#include "ModelBase.h"

#include "EffectType.h"
#include "EffectInput_param.h"

namespace ChromaPackage {
namespace Model {

/// <summary>
/// JSON Data
/// </summary>
class  EffectInput
    : public ModelBase
{
public:
    EffectInput();
    virtual ~EffectInput();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// EffectInput members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<EffectType> getEffect() const;
    void setEffect(std::shared_ptr<EffectType> value);
        /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<EffectInput_param> getParam() const;
    void setParam(std::shared_ptr<EffectInput_param> value);
    bool paramIsSet() const;
    void unsetParam();

protected:
    std::shared_ptr<EffectType> m_Effect;
    std::shared_ptr<EffectInput_param> m_Param;
    bool m_ParamIsSet;
};

}
}

#endif /* EffectInput_H_ */
