/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "EffectResponse.h"

namespace ChromaPackage {
namespace Model {

EffectResponse::EffectResponse()
{
    m_Result = 0;
    
}

EffectResponse::~EffectResponse()
{
}

void EffectResponse::validate()
{
    // TODO: implement validation
}

web::json::value EffectResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    val[U("result")] = ModelBase::toJson(m_Result);
    

    return val;
}

void EffectResponse::fromJson(web::json::value& val)
{
    setResult(ModelBase::int32_tFromJson(val[U("result")]));
    
}

void EffectResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + U("result"), m_Result));
    
}

void EffectResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    setResult(ModelBase::int32_tFromHttpContent(multipart->getContent(U("result"))));
    
}


int32_t EffectResponse::getResult() const
{
    return m_Result;
}
void EffectResponse::setResult(int32_t value)
{
    m_Result = value;
    
}

}
}

