/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * EffectIdentifierInput.h
 *
 * 
 */

#ifndef EffectIdentifierInput_H_
#define EffectIdentifierInput_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace ChromaPackage {
namespace Model {

/// <summary>
/// 
/// </summary>
class  EffectIdentifierInput
    : public ModelBase
{
public:
    EffectIdentifierInput();
    virtual ~EffectIdentifierInput();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// EffectIdentifierInput members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    void setId(utility::string_t value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getIds();
    bool idsIsSet() const;
    void unsetIds();

protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
std::vector<utility::string_t> m_Ids;
    bool m_IdsIsSet;
};

}
}

#endif /* EffectIdentifierInput_H_ */
