/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * EffectType.h
 *
 * Chroma generic effects. Note that not all devices supported the listed effects
 */

#ifndef EffectType_H_
#define EffectType_H_


#include "ModelBase.h"


namespace ChromaPackage {
namespace Model {

/// <summary>
/// Chroma generic effects. Note that not all devices supported the listed effects
/// </summary>
class  EffectType
    : public ModelBase
{
public:
    EffectType();
    virtual ~EffectType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// EffectType members


protected:
    };

}
}

#endif /* EffectType_H_ */
