/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "EffectResponseId.h"

namespace ChromaPackage {
namespace Model {

EffectResponseId::EffectResponseId()
{
    m_Id = U("");
    m_IdIsSet = false;
    m_Result = 0;
    
}

EffectResponseId::~EffectResponseId()
{
}

void EffectResponseId::validate()
{
    // TODO: implement validation
}

web::json::value EffectResponseId::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_IdIsSet)
    {
        val[U("id")] = ModelBase::toJson(m_Id);
    }
    val[U("result")] = ModelBase::toJson(m_Result);
    

    return val;
}

void EffectResponseId::fromJson(web::json::value& val)
{
    if(val.has_field(U("id")))
    {
        setId(ModelBase::stringFromJson(val[U("id")]));
        
    }
    setResult(ModelBase::int32_tFromJson(val[U("result")]));
    
}

void EffectResponseId::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("id"), m_Id));
        
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("result"), m_Result));
    
}

void EffectResponseId::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("id")))
    {
        setId(ModelBase::stringFromHttpContent(multipart->getContent(U("id"))));
        
    }
    setResult(ModelBase::int32_tFromHttpContent(multipart->getContent(U("result"))));
    
}


utility::string_t EffectResponseId::getId() const
{
    return m_Id;
}
void EffectResponseId::setId(utility::string_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool EffectResponseId::idIsSet() const
{
    return m_IdIsSet;
}
void EffectResponseId::unsetId()
{
    m_IdIsSet = false;
}
int32_t EffectResponseId::getResult() const
{
    return m_Result;
}
void EffectResponseId::setResult(int32_t value)
{
    m_Result = value;
    
}

}
}

