/**
 * Chroma Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "EffectIdentifierResponse.h"

namespace ChromaPackage {
namespace Model {

EffectIdentifierResponse::EffectIdentifierResponse()
{
    m_Result = 0;
    m_ResultIsSet = false;
    m_ResultsIsSet = false;
    
}

EffectIdentifierResponse::~EffectIdentifierResponse()
{
}

void EffectIdentifierResponse::validate()
{
    // TODO: implement validation
}

web::json::value EffectIdentifierResponse::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_ResultIsSet)
    {
        val[U("result")] = ModelBase::toJson(m_Result);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Results )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            val[U("results")] = web::json::value::array(jsonArray);
        }
    }
    

    return val;
}

void EffectIdentifierResponse::fromJson(web::json::value& val)
{
    if(val.has_field(U("result")))
    {
        setResult(ModelBase::int32_tFromJson(val[U("result")]));
    }
    {
        m_Results.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("results")))
        {
        for( auto& item : val[U("results")].as_array() )
        {
            
            if(item.is_null())
            {
                m_Results.push_back( std::shared_ptr<EffectIdentifierResponse_results>(nullptr) );
            }
            else
            {
                std::shared_ptr<EffectIdentifierResponse_results> newItem(new EffectIdentifierResponse_results());
                newItem->fromJson(item);
                m_Results.push_back( newItem );
            }
            
        }
        }
    }
    
}

void EffectIdentifierResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_ResultIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("result"), m_Result));
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Results )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("results"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
    
}

void EffectIdentifierResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("result")))
    {
        setResult(ModelBase::int32_tFromHttpContent(multipart->getContent(U("result"))));
    }
    {
        m_Results.clear();
        if(multipart->hasContent(U("results")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("results"))));
        for( auto& item : jsonArray.as_array() )
        {
            
            if(item.is_null())
            {
                m_Results.push_back( std::shared_ptr<EffectIdentifierResponse_results>(nullptr) );
            }
            else
            {
                std::shared_ptr<EffectIdentifierResponse_results> newItem(new EffectIdentifierResponse_results());
                newItem->fromJson(item);
                m_Results.push_back( newItem );
            }
            
        }
        }
    }
    
}


int32_t EffectIdentifierResponse::getResult() const
{
    return m_Result;
}
void EffectIdentifierResponse::setResult(int32_t value)
{
    m_Result = value;
    m_ResultIsSet = true;
}
bool EffectIdentifierResponse::resultIsSet() const
{
    return m_ResultIsSet;
}
void EffectIdentifierResponse::unsetResult()
{
    m_ResultIsSet = false;
}
std::vector<std::shared_ptr<EffectIdentifierResponse_results>>& EffectIdentifierResponse::getResults()
{
    return m_Results;
}
bool EffectIdentifierResponse::resultsIsSet() const
{
    return m_ResultsIsSet;
}
void EffectIdentifierResponse::unsetResults()
{
    m_ResultsIsSet = false;
}

}
}

