/**
 * Razer REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DefaultApi.h
 *
 * 
 */

#ifndef DefaultApi_H_
#define DefaultApi_H_


#include "ApiClient.h"

#include "ChromaSdkInput.h"
#include "PostChromaSdkResponse.h"

namespace ChromaPackage {

using namespace ChromaPackage::Model;

class  DefaultApi
{
public:
    DefaultApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~DefaultApi();
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Initialize the Chroma SDK
    /// </remarks>
    /// <param name="baseInput"> (optional)</param>
    pplx::task<std::shared_ptr<PostChromaSdkResponse>> postChromaSdk(std::shared_ptr<ChromaSdkInput> baseInput);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}

#endif /* DefaultApi_H_ */

